{% set name = "parsimonious" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parsimonious-{{ version }}.tar.gz
  sha256: 8281600da180ec8ae35427a4ab4f7b82bfec1e3d1e52f80cb60ea82b9512501c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - regex

test:
  imports:
    - parsimonious
  commands:
    - ls
    - pwd
    - python -m pytest --tb=native parsimonious
  requires:
    - pytest

about:
  home: https://github.com/erikrose/parsimonious/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: (Soon to be) the fastest pure-Python PEG parser I could muster
  description: (Soon to be) the fastest pure-Python PEG parser I could muster
  doc_url: https://github.com/erikrose/parsimonious/
  dev_url: https://github.com/erikrose/parsimonious/

extra:
  recipe-maintainers:
    - nelson-liu
    - lucaswiman
    - enekomartinmartinez
