travis:
  secure:
    BINSTAR_TOKEN: Pgs6lDvbiUVoctFgG5buZWy+S4oNg32sajPRhMMTrLKwuF1mU5Q/gOsaQthtJRD8GX6pkhKqg1vNIHKG4tsaOzCEtRj1753w2+ChaUIZN/TrjBoDpHqHqPfymD2vr1ua3i9phXSJBY006/0LF5ju0Z40JEOgZs48g3QeWugu9x12F0GsDL0iR8SSfOOxsaPSUt33HkhJGlcYT5ZpAWGTs2Vw89Z5ws5ZOf2qoLA6wmzpel7lZrNES+VPS91D9LZDJjmfIaZ7naRUc9dNtBUas2uOCU9dU6KwUR3plPyGf8vi2PvQg0P+tNV0FXWRa4OmduM45dnQVGWsKWYqj58n/k3x5cS2L7TcEDkZ3PQfrORcSfLHNlYaEUBvvvCdLtQgMvGNvmVVA3WhWSCzWPhsHirwgTkb4yxa1xdVt9eKSVpfr/58Ai+3YlK9MToNaY/Gl7a+TGq2qcfYCtBxHnZUgbs1UiKbYbtoB3sF9CVkktBDV+Bvnl6bbx5PdoWn+HSeTHY1Wtia1SR5DdLrrxwQfirQ6bJqzev+qEbwRIEU0dJ50zuHBvWIB2mI+BYvScmj0/0p/Rzkpm6kwLHc8IWQzuesW+6ChQPcyZjGNs2UNCaATV5RLECRi4vD6U5deBiLW6DFqGax1NuUuXFqDjypoM6IwjBt2rbbGyGd2s2BVEY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
